// <auto-generated />
using System;
using GlutenFreeVictuals.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GlutenFreeVictuals.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181201194243_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GlutenFreeVictuals.Models.Rating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RatingScore");

                    b.Property<int?>("RecipeID");

                    b.Property<int?>("UserID");

                    b.HasKey("RatingID");

                    b.HasIndex("RecipeID");

                    b.HasIndex("UserID");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("GlutenFreeVictuals.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CookTimeMinutes");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Ingredients")
                        .IsRequired();

                    b.Property<string>("Instructions")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PrepTimeMinutes");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int?>("UserID");

                    b.HasKey("RecipeID");

                    b.HasIndex("UserID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("GlutenFreeVictuals.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GlutenFreeVictuals.Models.Rating", b =>
                {
                    b.HasOne("GlutenFreeVictuals.Models.Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeID");

                    b.HasOne("GlutenFreeVictuals.Models.User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("GlutenFreeVictuals.Models.Recipe", b =>
                {
                    b.HasOne("GlutenFreeVictuals.Models.User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
